# -*- coding: utf-8 -*-
"""Hyderabad_NO2_Main_Model_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTXEbIPXPjyQNgaztSE_ByG0xEJBE0Bt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = pd.read_csv(
    "prototype1_hyderabad_ml_dataset_jan2025.csv"
)

data.head()

print("Shape:", data.shape)

print("\nColumns:")
print(data.columns.tolist())

print("\nMissing values:")
print(data.isna().sum())

features = [
    "temperature_c",
    "wind_speed_m_s",
    "population_density_persons_per_km2",
    "road_density_km_per_km2"
]

X = data[features]

y = data["no2_mol_m2"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nINPUTS:")
print(X.head())

print("\nTARGET:")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

predictions

results = data.loc[X_test.index, [
    "grid_id",
    "temperature_c",
    "wind_speed_m_s",
    "population_density_persons_per_km2",
    "road_density_km_per_km2",
    "no2_mol_m2"
]].copy()

results["predicted_no2"] = predictions

results = results[
    [
        "grid_id",
        "temperature_c",
        "wind_speed_m_s",
        "population_density_persons_per_km2",
        "road_density_km_per_km2",
        "no2_mol_m2",
        "predicted_no2"
    ]
]

results.head(10)

mae = mean_absolute_error(y_test, predictions)

rmse = np.sqrt(
    mean_squared_error(y_test, predictions)
)

r2 = r2_score(
    y_test,
    predictions
)

print("MAIN MODEL V1 RESULTS")
print("----------------------")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

mape = np.mean(
    np.abs((y_test - predictions) / y_test)
) * 100

print("MAPE:", mape, "%")

train_predictions = model.predict(X_train)

train_r2 = r2_score(y_train, train_predictions)
test_r2 = r2_score(y_test, predictions)

print("Training R²:", train_r2)
print("Testing R² :", test_r2)

print(data[["grid_id", "no2_mol_m2"]].head(20))

print(data["grid_id"].tolist()[:20])

import geopandas as gpd
grid = gpd.read_file("/content/hyderabad_orr_1km_mastergrid.zip")

data_with_geometry = grid.merge(
    data,
    on="grid_id",
    how="inner"
)

print("Merged cells:", len(data_with_geometry))

print("\nCRS:")
print(data_with_geometry.crs)

print("\nColumns:")
print(data_with_geometry.columns.tolist())

grid_projected = data_with_geometry.to_crs(epsg=32644)

grid_projected["centroid"] = grid_projected.geometry.centroid

grid_projected["x"] = grid_projected.centroid.x
grid_projected["y"] = grid_projected.centroid.y

grid_projected[["grid_id", "x", "y"]].head()

print("X range:")
print(grid_projected["x"].min(), "to", grid_projected["x"].max())

print("\nY range:")
print(grid_projected["y"].min(), "to", grid_projected["y"].max())

grid_projected["x_block"] = pd.cut(
    grid_projected["x"],
    bins=4,
    labels=False
)

grid_projected["y_block"] = pd.cut(
    grid_projected["y"],
    bins=4,
    labels=False
)

grid_projected["spatial_block"] = (
    grid_projected["x_block"].astype(str)
    + "_"
    + grid_projected["y_block"].astype(str)
)

print(
    grid_projected[
        ["grid_id", "x_block", "y_block", "spatial_block"]
    ].head(20)
)

print(
    grid_projected["spatial_block"]
    .value_counts()
    .sort_index()
)

TEST_BLOCKS = ["2_0", "2_1"]

train_data = grid_projected[
    ~grid_projected["spatial_block"].isin(TEST_BLOCKS)
].copy()

test_data = grid_projected[
    grid_projected["spatial_block"].isin(TEST_BLOCKS)
].copy()

print("Training observations:", len(train_data))
print("Testing observations:", len(test_data))

print("TRAIN BLOCKS:")
print(
    train_data["spatial_block"]
    .value_counts()
    .sort_index()
)

print("\nTEST BLOCKS:")
print(
    test_data["spatial_block"]
    .value_counts()
    .sort_index()
)

features = [
    "temperature_c",
    "wind_speed_m_s",
    "population_density_persons_per_km2",
    "road_density_km_per_km2"
]

X_train = train_data[features]
y_train = train_data["no2_mol_m2"]

X_test = test_data[features]
y_test = test_data["no2_mol_m2"]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

spatial_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

spatial_model.fit(X_train, y_train)

spatial_predictions = spatial_model.predict(X_test)

spatial_results = test_data[
    [
        "grid_id",
        "spatial_block",
        "temperature_c",
        "wind_speed_m_s",
        "population_density_persons_per_km2",
        "road_density_km_per_km2",
        "no2_mol_m2"
    ]
].copy()

spatial_results["predicted_no2"] = spatial_predictions

spatial_results.head(20)

spatial_mae = mean_absolute_error(
    y_test,
    spatial_predictions
)

spatial_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        spatial_predictions
    )
)

spatial_r2 = r2_score(
    y_test,
    spatial_predictions
)

spatial_mape = np.mean(
    np.abs(
        (y_test - spatial_predictions) / y_test
    )
) * 100

print("SPATIAL TEST RESULTS")
print("--------------------")
print("MAE :", spatial_mae)
print("RMSE:", spatial_rmse)
print("R²  :", spatial_r2)
print("MAPE:", spatial_mape, "%")

from sklearn.ensemble import ExtraTreesRegressor

extra_model = ExtraTreesRegressor(
    n_estimators=200,
    random_state=42,
    max_features=1.0,
    min_samples_leaf=1
)

extra_model.fit(X_train, y_train)

extra_predictions = extra_model.predict(X_test)

extra_mae = mean_absolute_error(
    y_test,
    extra_predictions
)

extra_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        extra_predictions
    )
)

extra_r2 = r2_score(
    y_test,
    extra_predictions
)

extra_mape = np.mean(
    np.abs(
        (y_test - extra_predictions) / y_test
    )
) * 100

print("EXTRA TREES")
print("-----------")
print("MAE :", extra_mae)
print("RMSE:", extra_rmse)
print("R²  :", extra_r2)
print("MAPE:", extra_mape, "%")

import xgboost as xgb

xgb_model = xgb.XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=1.0,
    random_state=42,
    objective="reg:squarederror"
)

xgb_model.fit(X_train, y_train)

xgb_predictions = xgb_model.predict(X_test)

xgb_mae = mean_absolute_error(
    y_test,
    xgb_predictions
)

xgb_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        xgb_predictions
    )
)

xgb_r2 = r2_score(
    y_test,
    xgb_predictions
)

xgb_mape = np.mean(
    np.abs(
        (y_test - xgb_predictions) / y_test
    )
) * 100

print("XGBOOST")
print("-------")
print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)
print("R²  :", xgb_r2)
print("MAPE:", xgb_mape, "%")

leaderboard = pd.DataFrame({
    "Model": [
        "Random Forest",
        "Extra Trees",
        "XGBoost"
    ],

    "MAE": [
        spatial_mae,
        extra_mae,
        xgb_mae
    ],

    "RMSE": [
        spatial_rmse,
        extra_rmse,
        xgb_rmse
    ],

    "R2": [
        spatial_r2,
        extra_r2,
        xgb_r2
    ],

    "MAPE_%": [
        spatial_mape,
        extra_mape,
        xgb_mape
    ]
})

leaderboard = leaderboard.sort_values(
    "R2",
    ascending=False
).reset_index(drop=True)

leaderboard